apiVersion: apps/v1
kind: Deployment
metadata:
  name: myframeservice-app
  labels:
    app: myframeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myframeservice
  template:
    metadata:
      labels:
        app: myframeservice
    spec:
      containers:
      - name: myframeservice
        image: angelakimichellle/myframeservice:1.4
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "1"
            memory: "256Mi"
