apiVersion: v1
kind: Service
metadata:
  name: myframeservice-app
spec:
  selector:
    app: myframeservice
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  externalIPs:
  - 192.168.1.13
